### ISSUE TITLE
Potential for more Horse Camera options?

### ISSUE THREAD

**Issue by EDGE-ELITE** [Aelto/tw3-smart-camera#2]
I'm very happy with Smart Camera Core, it's a major improvement over the vanilla combat camera when playing on a gamepad.

Would it be possible to include a zoom (Y Translation) slider for the horse camera part of this mod? It would be great if a few options from the Core Smart Camera mod could be added to the Horse Camera (as separate options), as I find the default zoom quite far away on my small monitor. An auto-centre option that comes into effect when cantering/galloping would be a great addition too, if possible?

**Comment by Aelto** [comment]
Hello!

I'm glad you like the mod, thank you.

Sure i could add a few more options. I can't promise much since the horse camera code is quite complex, but a zoom slider should be possible.

The horse camera already has an autocenter thing if i remember correctly. It activates automatically if you aim in a ~10 degrees angle in front of you, and it disables itself as sson as you move the camera out of this cone. This cone gets bigger as the horse goes faster.

**Comment by EDGE-ELITE** [comment]
My apologies, you're right. I've just experimented with it some more, and it does indeed auto-centre. As for a zoom slider, if it is possible to add it, that would be fantastic.
I'd never even considered a camera mod until I had the vertical camera drift issue when on horseback, but I'm glad I did, as I found this one. Thank you again.

**Comment by Aelto** [comment]
I experimented with the new slider to control the zoom level, you can find a pre-release with the changes [here](https://github.com/Aelto/tw3-smart-camera/releases/tag/v1.9). Test it and report back if it is what you expected!

**Comment by EDGE-ELITE** [comment]
That's much better! I've tried it out for 20 minutes or so and it all appears to work as intended. Thank you so much for the speedy addition, I was very surprised to find an email this morning stating you'd already added the feature.

**Comment by Aelto** [comment]
Perfect then! I will close the issue and mark the release as complete.
