### ISSUE TITLE
Zoom bug when entering houses

### ISSUE THREAD

**Issue by xowny** [Aelto/tw3-smart-camera#4]
When entering a house the camera zoom in and gets all over the place https://i.imgur.com/Qar3A4c.jpg

i have the horse, exploration, boat and combat cams enabled, latest steam version.

**Comment by Aelto** [comment]
Hi, thanks for the issue. Can you confirm your settings are all properly set up ?

**Comment by xowny** [comment]
yes, all default settings except bounty markers enabled.

**Comment by Aelto** [comment]
bounty markers, this is from RER. What about the Smart Camera settings?

**Comment by xowny** [comment]
thats right was using that too, smart camera all default settings except the 4 cams enabled as i said earlier.

**Comment by Aelto** [comment]
Interesting. The fact it happens only in **houses** (can you confirm it is HOUSES and not HORSES) suggests me you're using another camera mod alongside Smart Camera, am i right? The mod does almost nothing while in exploration mode, and it does not even check for houses either, which is why i'm wondering if you're using another mod.

Someone once reported the same kind of zoom but while on ho**rses**, he fixed the issue by downloading the mod again and ensuring he was using the latest version. He also re-merged his files in the process, maybe it is related.

**Comment by xowny** [comment]
not using any other camera mods, and yes the zoom was "triggered" right after entering a house, after that even if i reloaded the save it was still there but now even outside, i did as you said, redownloaded everything and remerged the scripts, seems ok now, strange.

**Comment by Aelto** [comment]
There are cases where i quickly re-upload releases because i forget stuff, maybe you download the faulty version before i had the time to reupload it. It is now fixed though so it's all good!
